formatter: "markdown table" # this is required
version: "0.17.0"
header-from: main.tf
footer-from: ""
recursive:
  enabled: false
  path: ""
sections:
  hide: []
  show: []
  hide-all: false # deprecated in v0.13.0, removed in v0.15.0
  show-all: true  # deprecated in v0.13.0, removed in v0.15.0
content: |-
# Terraform AWS Infrastructure Deployment

This project uses Terraform to provision and manage AWS resources for a robust and scalable web application environment. It encompasses configurations for network resources, compute instances, storage, monitoring, and security, ensuring a highly available and secure application deployment.

## Overview

Our Terraform setup orchestrates the creation and management of the following AWS resources:

### Networking

- **VPC Fetching (`vpc-fetch.tf`)**: Retrieves existing VPC and subnet information, ensuring resources are correctly placed within the network.

### Compute Resources

- **EC2 Instances (`ec2.tf`)**: Provisions web servers or applications on EC2 instances, optimized for performance and cost.

- **Application Load Balancers (ALB) (`alb-private.tf`)**: Distributes incoming traffic across EC2 instances to improve availability.

### Storage

- **EBS Volumes (`ebs-volume.tf`)**: Provides additional or specialized storage for EC2 instances.

### Security

- **Security Groups (`security-group.tf`)**: Controls access to EC2 instances and ALBs with firewall rules.

### Monitoring

- **CloudWatch Monitoring (`monitoring.tf`)**: Sets up alarms and notifications for infrastructure monitoring with Amazon CloudWatch.

### Outputs

- **Outputs (`output.tf`)**: Displays important information such as IP addresses and DNS names of the resources.

### Configuration

- **Variables (`variables.tf`)**: Allows customization of the deployment through input variables.

- **Local Values (`locals.tf`)**: Simplifies configuration by defining common constants and calculated values.

## For Non-Technical Stakeholders

This project automates the setup of our web application infrastructure on AWS. It's designed to be secure, scalable, and monitored, ensuring optimal performance and availability. Terraform allows for easy adjustments and consistent environments across development, staging, and production.

### Key Benefits

- **Scalability**: Adjust resources to meet demand.
- **Security**: Ensure application protection through customizable firewall rules.
- **High Availability**: Maintain application performance and availability through load balancing and monitoring.
- **Cost-Effectiveness**: Scale resources according to use, minimizing costs.

## Getting Started

To use this module for deploying your AWS infrastructure, follow these steps:

1. Ensure you have Terraform installed and configured.
2. Clone this repository to your local machine.
3. Navigate to the cloned repository and update the `variables.tf` file with your specific configuration values.
4. Initialize Terraform to download necessary providers and set up the backend:
   ```
   terraform init
   ```
5. Apply the Terraform configuration to create the resources in AWS:
   ```
   terraform apply
   ```
6. Confirm the action by typing `yes` when prompted.

## Contributing

Contributions to this project are welcome! To contribute, please follow these steps:

1. Fork the repository.
2. Create a new branch for your feature or fix.
3. Commit your changes with clear, descriptive messages.
4. Push your branch and submit a pull request.

Please note that this project adheres to a code of conduct. By participating, you are expected to uphold this code.

### Maintainer

- [@w4ss1m]- For any questions or suggestions.
  {{ .Requirements }}
  ## Usage
  Basic usage of this module is as follows:
  ```hcl
  module "example" {
    {{"\t"}} source  = "<module-path>"
    {{- if .Module.RequiredInputs }}
    {{"\n\t"}} # Required variables
    {{- range .Module.RequiredInputs }}
    {{"\t"}} {{ .Name }}  = {{ .GetValue }}
    {{- end }}
    {{- end }}
    {{- if .Module.OptionalInputs }}
    {{"\n\t"}} # Optional variables
    {{- range .Module.OptionalInputs }}
    {{"\t"}} {{ .Name }}  = {{ .GetValue | printf "%s" }}
    {{- end }}
    {{- end }}
  }
  ```
    {{ .Resources }}
    {{ .Inputs }}
    {{ .Outputs }}
output:
  file: README.md
  mode: inject
  template: |-
      <!-- BEGIN_AUTOMATED_TF_DOCS_BLOCK -->
      {{ .Content }}
      <!-- END_AUTOMATED_TF_DOCS_BLOCK -->
output-values:
  enabled: false
  from: ""
sort:
  enabled: true
  by: name
settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
